<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNFxLp8x\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNFxLp8x/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerNFxLp8x.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerNFxLp8x\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerNFxLp8x\appAppKernelProdContainer([
    'container.build_hash' => 'NFxLp8x',
    'container.build_id' => '2f0c1c86',
    'container.build_time' => 1679087559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNFxLp8x');
